version: '3.7'
name: laravel_websockets
networks:
    net:
        driver: bridge
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        container_name: lw_server
        ports:
            - ${SERVER_PORT}:80
            - ${VITE_PORT}:5173
            - ${WEBSOCKETS_PORT}:6001
        volumes:
            - ../:/var/www/html
            - /var/www/html/docker/data
            - /var/www/html/node_modules
        networks:
            - net
        depends_on:
            - mysql
            - redis
        environment:
            SERVER_PORT: ${SERVER_PORT}
    mysql:
        container_name: lw_mysql
        image: mysql:8
        command: --max_allowed_packet=92505856
        networks:
            - net
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
    redis:
        image: redis:6
        container_name: lw_redis
        networks:
            - net
        volumes:
            - ./data/redis:/data/redis
        ports:
            - ${REDIS_PORT}:6379
